"""initial_schema

Revision ID: 3b3829b2f765
Revises: 
Create Date: 2026-10-06 12:44:59.233113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3829b2f765'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('jaccard_similarity', sa.Float(), nullable=True))
    op.add_column('analysis_results', sa.Column('containment_similarity', sa.Float(), nullable=True))
    op.add_column('analysis_results', sa.Column('ast_similarity', sa.Float(), nullable=True))
    op.add_column('analysis_results', sa.Column('is_exact_duplicate', sa.Boolean(), nullable=False))
    op.alter_column('analysis_results', 'suspicious',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               nullable=False)
    op.create_unique_constraint('uq_analysis_result_pair', 'analysis_results', ['session_id', 'submission_a_id', 'submission_b_id'])
    op.add_column('submissions', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_submissions_content_hash'), 'submissions', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_content_hash'), table_name='submissions')
    op.drop_column('submissions', 'content_hash')
    op.drop_constraint('uq_analysis_result_pair', 'analysis_results', type_='unique')
    op.alter_column('analysis_results', 'suspicious',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('analysis_results', 'is_exact_duplicate')
    op.drop_column('analysis_results', 'ast_similarity')
    op.drop_column('analysis_results', 'containment_similarity')
    op.drop_column('analysis_results', 'jaccard_similarity')
    # ### end Alembic commands ###
